cmd_drivers/misc/fusb302/core/vdm/DisplayPort/configure.o := ./scripts/gcc-wrapper.py /home/mandysingh/RR/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-gcc -Wp,-MD,drivers/misc/fusb302/core/vdm/DisplayPort/.configure.o.d  -nostdinc -isystem /home/mandysingh/RR/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/../lib/gcc/arm-eabi/4.8/include -I./arch/arm/include -Iarch/arm/include/generated  -Iinclude -I./arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-msm/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -fno-PIE -Os -Wno-maybe-uninitialized --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -DFSC_PLATFORM_LINUX -DFSC_INTERRUPT_TRIGGERED -DFSC_DEBUG -DFSC_HAVE_SRC -DFSC_HAVE_SNK -DFSC_HAVE_DRP -DFSC_HAVE_ACCMODE -DFSC_HAVE_VDM -DFSC_HAVE_DP    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(configure)"  -D"KBUILD_MODNAME=KBUILD_STR(fusb302)" -c -o drivers/misc/fusb302/core/vdm/DisplayPort/.tmp_configure.o drivers/misc/fusb302/core/vdm/DisplayPort/configure.c

source_drivers/misc/fusb302/core/vdm/DisplayPort/configure.o := drivers/misc/fusb302/core/vdm/DisplayPort/configure.c

deps_drivers/misc/fusb302/core/vdm/DisplayPort/configure.o := \
  drivers/misc/fusb302/core/vdm/DisplayPort/configure.h \

drivers/misc/fusb302/core/vdm/DisplayPort/configure.o: $(deps_drivers/misc/fusb302/core/vdm/DisplayPort/configure.o)

$(deps_drivers/misc/fusb302/core/vdm/DisplayPort/configure.o):
